[package]
name = "uber-eats-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
bigdecimal = { version = "0.4.8", features = ["serde"] }
chrono = { version = "0.4.42", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "mysql", "chrono", "bigdecimal"] }
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.6.6", features = ["cors"] }
